# Generated by Django 2.1.5 on 2019-01-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190121_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Enter the book language (e.g. English, French, Japanese etc.)', max_length=200),
        ),
    ]
