# Generated by Django 2.1.5 on 2019-01-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190121_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text="Enter the book's language (e.g. English, French, Japanese etc.)", max_length=200),
        ),
    ]
